apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: <your-ecr-repo-url>:latest  # Replace with your actual ECR image
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "mywebdb.cujue22kskdi.us-east-1.rds.amazonaws.com"
            - name: WORDPRESS_DB_USER
              value: "admin"
            - name: WORDPRESS_DB_PASSWORD
              value: "Calvin17"
            - name: WORDPRESS_DB_NAME
              value: "login"
