apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: your_ecr_repository:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "your_rds_endpoint"
            - name: WORDPRESS_DB_USER
              value: "your_database_user"
            - name: WORDPRESS_DB_PASSWORD
              value: "your_database_password"
            - name: WORDPRESS_DB_NAME
              value: "your_database_name"